# Dockerfile-golang
FROM golang:1.18-alpine
WORKDIR /app

COPY backend-app/go.mod .
COPY backend-app/go.sum .

# airの設定ファイルをコピー
COPY backend-app/*air.toml .

RUN go mod download

COPY ./backend-app .

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

RUN go get -d github.com/cosmtrek/air
RUN go install github.com/cosmtrek/air
# RUN apk --no-cache add ca-certificates wget && \
#     wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
#     wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.34-r0/glibc-2.34-r0.apk && \
#     apk add glibc-2.34-r0.apk && \
#     rm glibc-2.34-r0.apk && \
#     apk del wget ca-certificates

CMD ["air"]
